
# Anexos {#Anexos}

Anexos

## Descripción de las series

<center>
|Code	|Indicator Name|
|-----|-------------------------------------------------------------|
|SP.POP.TOTL|	Population, total|
|SL.UEM.TOTL.NE.ZS|	Unemployment, total (% of total labor force) (national estimate)|
|NY.GDP.MKTP.CN|	GDP (current LCU)|
</center>


|Code	|Indicator Name |	Long definition |	Source|
|-----|---------------|--------------------------------------------------------|-------|
|SP.POP.TOTL	|Population, total	|Total population is based on the de facto definition of population, which counts all residents regardless of legal status or citizenship. The values shown are midyear estimates.	|(1) United Nations Population Division. World Population Prospects, (2) Census reports and other statistical publications from national statistical offices, (3) Eurostat: Demographic Statistics, (4) United Nations Statistical Division. Population and Vital Statistics Report (various years), (5) U.S. Census Bureau: International Database, and (6) Secretariat of the Pacific Community: Statistics and Demography Programme.|
|SL.UEM.TOTL.NE.ZS	|Unemployment, total (% of total labor force) (national estimate)	|Unemployment refers to the share of the labor force that is without work but available for and seeking employment. Definitions of labor force and unemployment differ by country.	|International Labour Organization, ILOSTAT database. Data retrieved in March 2017.|
|SH.XPD.PUBL.ZS	|Health expenditure, public (% of GDP)	|Public health expenditure consists of recurrent and capital spending from government (central and local) budgets, external borrowings and grants (including donations from international agencies and nongovernmental organizations), and social (or compulsory) health insurance funds.	|World Health Organization Global Health Expenditure database (see http://apps.who.int/nha/database for the most recent updates).|
|NY.GDP.MKTP.CN	|GDP (current LCU)	|GDP at purchaser's prices is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources. Data are in current local currency.	|World Bank national accounts data, and OECD National Accounts data files.|

## Bibliografia

http://otexts.org/fpp2/intro.html

http://www.pfaffikus.de/files/conf/user/useR2008.pdf

http://www.mexicomaxico.org/Voto/PIBMex.htm

https://www.mexicoevalua.org/wp-content/uploads/2016/05/MEX_EVA-INHOUS-GASTO_SALUD-LOW.pdf


## Dudas




