<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Código Tesis</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Código Tesis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Código Tesis" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Omar Díaz Landa">


<meta name="date" content="2019-03-12">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="orden-de-integracion-teoria.html">
<link rel="next" href="orden-de-integracion-lnpib-a-precios-corrientes.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Tesis Omar Díaz Landa</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisitos</a></li>
<li class="chapter" data-level="2" data-path="datos.html"><a href="datos.html"><i class="fa fa-check"></i><b>2</b> Lectura de datos</a><ul>
<li class="chapter" data-level="2.1" data-path="datos.html"><a href="datos.html#graficamos-las-series-de-datos"><i class="fa fa-check"></i><b>2.1</b> Graficamos las series de datos</a><ul>
<li class="chapter" data-level="2.1.1" data-path="datos.html"><a href="datos.html#producto-interno-bruto"><i class="fa fa-check"></i><b>2.1.1</b> Producto Interno Bruto</a></li>
<li class="chapter" data-level="2.1.2" data-path="datos.html"><a href="datos.html#recaudacion-fiscal"><i class="fa fa-check"></i><b>2.1.2</b> Recaudación Fiscal</a></li>
<li class="chapter" data-level="2.1.3" data-path="datos.html"><a href="datos.html#gasto-en-salud-publica"><i class="fa fa-check"></i><b>2.1.3</b> Gasto en Salud Pública</a></li>
<li class="chapter" data-level="2.1.4" data-path="datos.html"><a href="datos.html#gasto-en-educacion-publica"><i class="fa fa-check"></i><b>2.1.4</b> Gasto en Educación Pública</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="orden-de-integracion-teoria.html"><a href="orden-de-integracion-teoria.html"><i class="fa fa-check"></i><b>3</b> Orden de Integración (Teoría)</a></li>
<li class="chapter" data-level="4" data-path="orden-integracion-pib-a-precios-corrientes.html"><a href="orden-integracion-pib-a-precios-corrientes.html"><i class="fa fa-check"></i><b>4</b> Orden Integración PIB a precios corrientes</a></li>
<li class="chapter" data-level="5" data-path="orden-de-integracion-lnpib-a-precios-corrientes.html"><a href="orden-de-integracion-lnpib-a-precios-corrientes.html"><i class="fa fa-check"></i><b>5</b> Orden de Integración ln(PIB) a precios corrientes</a></li>
<li class="chapter" data-level="6" data-path="orden-integracion-de-la-serie-recaudacion-impositiva.html"><a href="orden-integracion-de-la-serie-recaudacion-impositiva.html"><i class="fa fa-check"></i><b>6</b> Orden Integración de la serie Recaudación Impositiva</a></li>
<li class="chapter" data-level="7" data-path="orden-integracion-de-la-serie-gasto-en-salud.html"><a href="orden-integracion-de-la-serie-gasto-en-salud.html"><i class="fa fa-check"></i><b>7</b> Orden Integración de la serie Gasto en Salud</a></li>
<li class="chapter" data-level="8" data-path="orden-integracion-de-la-serie-gasto-en-educacion.html"><a href="orden-integracion-de-la-serie-gasto-en-educacion.html"><i class="fa fa-check"></i><b>8</b> Orden Integración de la serie Gasto en Educación</a></li>
<li class="chapter" data-level="9" data-path="orden-integracion-de-la-serie-lnpib-a-precios-ctes.html"><a href="orden-integracion-de-la-serie-lnpib-a-precios-ctes.html"><i class="fa fa-check"></i><b>9</b> Orden Integración de la serie ln(PIB) a precios ctes</a></li>
<li class="chapter" data-level="10" data-path="cointegracion-teoria.html"><a href="cointegracion-teoria.html"><i class="fa fa-check"></i><b>10</b> Cointegración (Teoría)</a></li>
<li class="chapter" data-level="11" data-path="cointegracion-analisis.html"><a href="cointegracion-analisis.html"><i class="fa fa-check"></i><b>11</b> Cointegración (Análisis)</a><ul>
<li class="chapter" data-level="11.1" data-path="cointegracion-analisis.html"><a href="cointegracion-analisis.html#determinacion-del-rango-de-cointegracion"><i class="fa fa-check"></i><b>11.1</b> Determinación del Rango de Cointegración</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="estimacion-del-modelo.html"><a href="estimacion-del-modelo.html"><i class="fa fa-check"></i><b>12</b> Estimación del modelo</a><ul>
<li class="chapter" data-level="12.1" data-path="estimacion-del-modelo.html"><a href="estimacion-del-modelo.html#modelo-1-vecm-con-k2-lags-y-r1-relaciones-de-cointegracion"><i class="fa fa-check"></i><b>12.1</b> Modelo 1: VECM con K=2 (lags), y r=1 (relaciones de cointegración)</a></li>
<li class="chapter" data-level="12.2" data-path="estimacion-del-modelo.html"><a href="estimacion-del-modelo.html#modelo-2-vecm-con-k2-lags-y-r2-relaciones-de-cointegracion"><i class="fa fa-check"></i><b>12.2</b> Modelo 2: VECM con K=2 (lags), y r=2 (relaciones de cointegración)</a></li>
<li class="chapter" data-level="12.3" data-path="estimacion-del-modelo.html"><a href="estimacion-del-modelo.html#modelo-3-vecm-con-k3-lags-y-r1-relaciones-de-cointegracion"><i class="fa fa-check"></i><b>12.3</b> Modelo 3: VECM con K=3 (lags), y r=1 (relaciones de cointegración)</a></li>
<li class="chapter" data-level="12.4" data-path="estimacion-del-modelo.html"><a href="estimacion-del-modelo.html#modelo-4-vecm-con-k3-lags-y-r2-relaciones-de-cointegracion"><i class="fa fa-check"></i><b>12.4</b> Modelo 4: VECM con K=3 (lags), y r=2 (relaciones de cointegración)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="13" data-path="interpolacion-serie-educacion.html"><a href="interpolacion-serie-educacion.html"><i class="fa fa-check"></i><b>13</b> Interpolación Serie Educación</a><ul>
<li class="chapter" data-level="13.1" data-path="interpolacion-serie-educacion.html"><a href="interpolacion-serie-educacion.html#version-2-del-pronositico"><i class="fa fa-check"></i><b>13.1</b> version 2 del pronositico</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="Anexos.html"><a href="Anexos.html"><i class="fa fa-check"></i><b>14</b> Anexos</a><ul>
<li class="chapter" data-level="14.1" data-path="Anexos.html"><a href="Anexos.html#descripcion-de-las-series"><i class="fa fa-check"></i><b>14.1</b> Descripción de las series</a></li>
<li class="chapter" data-level="14.2" data-path="Anexos.html"><a href="Anexos.html#bibliografia"><i class="fa fa-check"></i><b>14.2</b> Bibliografia</a></li>
<li class="chapter" data-level="14.3" data-path="Anexos.html"><a href="Anexos.html#dudas"><i class="fa fa-check"></i><b>14.3</b> Dudas</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Código Tesis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="orden-integracion-pib-a-precios-corrientes" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Orden Integración PIB a precios corrientes</h1>
<p>La serie de PIB a precios corrientes parece ser una serie con un orden de integración, esto será corroborado con las pruebas de hipótesis presentadas por Dickey &amp; Fuller, tal y como ya se ha presentado en la sección previa.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gf1 &lt;-<span class="st"> </span><span class="kw">grafica_serie</span>(<span class="dt">base_in =</span> series_db, 
                      <span class="dt">eje_y =</span> <span class="st">&#39;GDP_corriente&#39;</span>, 
                      <span class="dt">titulo =</span> <span class="st">&#39;PIB a precios corrientes&#39;</span>, 
                      <span class="dt">titulo_y =</span> <span class="st">&#39;PIB Corriente&#39;</span>)
gf1</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>En primer lugar necesitamos realizar la lectura de los datos como un objeto <em>ts</em> y posteriormente una regresión con una constante y tendencia temporal será estimada, en este caso en particular, no será necesario agregar lags a la estimación ya que no hay evidencia de presencia de autocorrelaciones y autocorrelaciones parciales diferentes de cero, por lo que podemos asegurar un proceso esférico del error. Incluir desde uno hasta el cuarto lag resultaban ser no significativos.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pib_corr &lt;-<span class="st"> </span><span class="kw">ts</span>(series_db<span class="op">$</span>GDP_corriente,<span class="dt">start =</span> <span class="dv">1991</span>, <span class="dt">end =</span> <span class="dv">2016</span>, <span class="dt">frequency =</span> <span class="dv">1</span>)
pib_corr.ct &lt;-<span class="st"> </span><span class="kw">ur.df</span>(pib_corr,<span class="dt">lags=</span><span class="dv">3</span>,<span class="dt">type=</span><span class="st">&#39;trend&#39;</span>)
<span class="kw">summary</span>(pib_corr.ct)</code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression trend 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 + 1 + tt + z.diff.lag)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -9.516e+11 -2.101e+11  6.205e+10  2.318e+11  4.160e+11 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  8.996e+11  6.242e+11   1.441    0.169  
## z.lag.1      4.345e-02  2.574e-01   0.169    0.868  
## tt           3.994e+09  1.925e+11   0.021    0.984  
## z.diff.lag1 -1.065e-01  2.791e-01  -0.381    0.708  
## z.diff.lag2 -1.885e-01  2.615e-01  -0.721    0.481  
## z.diff.lag3 -4.611e-01  2.384e-01  -1.934    0.071 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.648e+11 on 16 degrees of freedom
## Multiple R-squared:  0.3232, Adjusted R-squared:  0.1117 
## F-statistic: 1.528 on 5 and 16 DF,  p-value: 0.2364
## 
## 
## Value of test-statistic is: 0.1688 5.7828 2.9826 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau3 -4.15 -3.50 -3.18
## phi2  7.02  5.13  4.31
## phi3  9.31  6.73  5.61</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(pib_corr.ct)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Ahora bien la hipótesis <span class="math inline">\(\phi_3\)</span> es probada bajo una usual prueba F, es decir, <span class="math inline">\(\phi_3=(a_0,\gamma,a_2) = (a_0,0,0)\)</span>. Esto es, se han colocado restricciones igual a cero a la tendencia temporal y el lag del la variable.</p>
<p>El valor del estadístico es</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pib_corr.ct<span class="op">@</span>teststat</code></pre></div>
<pre><code>##                tau3     phi2     phi3
## statistic 0.1688183 5.782813 2.982571</code></pre>
<p>Debemos recordar que se deben consular los valores críticos propuestas por Dickey and Fuller. Los valores críticos para una muestra de tamaño 100 y niveles de significancia del 10%,5% y 1% se muestran a continuación</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pib_corr.ct<span class="op">@</span>cval</code></pre></div>
<pre><code>##       1pct  5pct 10pct
## tau3 -4.15 -3.50 -3.18
## phi2  7.02  5.13  4.31
## phi3  9.31  6.73  5.61</code></pre>
<p>Por lo tanto, la hipótesis nula no puede ser rechazada, lo cual implica que la serie contiene una raíz unitaria. Esto puede ser reiterado con el estadístico <span class="math inline">\(\tau_3\)</span> y para la variable <em>z.lag.1</em>. Los valores críticos relevantes que debemos utilizar ahora son los de Fuller[1976], los cuales se muestran para una muestra de tamaño 100.</p>
<p>Luego entonces, la presencia de una raíz unitaria no puede rechazada. El siguiente paso, es probar si la serie es una caminata aleatoria con o sin drift (constante).</p>
<p>El estadístico relevante es <span class="math inline">\(\phi_2\)</span> <span class="math inline">\((\gamma=a_0=a_2=0)\)</span> el cual tiene un valor de 3.738072, con valores críticos de 7.02 5.13 4.31 para niveles de significancia de 1%, 5% y 10% respectivamente. La conclusión es entonces que la serie no se comporta como una caminata aleatoria pura, ya que tiene una constante incluida en el proceso, así como un orden de integración.</p>
<p>Uno procede entonces a estimar la ecuación <span class="math inline">\(\nabla y_t = a_0 + \gamma y_{t-1} + \epsilon_t\)</span> basado en los resultados obtenidos por la prueba <span class="math inline">\(\phi_3\)</span>. Los resultados se muestran a continuación:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pib_corr.co &lt;-<span class="st"> </span><span class="kw">ur.df</span>(pib_corr,<span class="dt">lags=</span><span class="dv">3</span>,<span class="dt">type=</span><span class="st">&#39;drift&#39;</span>)
<span class="kw">summary</span>(pib_corr.co)</code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression drift 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -9.511e+11 -2.104e+11  6.060e+10  2.324e+11  4.157e+11 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  9.113e+11  2.589e+11   3.519  0.00263 **
## z.lag.1      4.877e-02  1.937e-02   2.517  0.02214 * 
## z.diff.lag1 -1.095e-01  2.292e-01  -0.478  0.63879   
## z.diff.lag2 -1.911e-01  2.243e-01  -0.852  0.40615   
## z.diff.lag3 -4.623e-01  2.246e-01  -2.058  0.05527 . 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.539e+11 on 17 degrees of freedom
## Multiple R-squared:  0.3232, Adjusted R-squared:  0.164 
## F-statistic:  2.03 on 4 and 17 DF,  p-value: 0.1357
## 
## 
## Value of test-statistic is: 2.5174 9.2159 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau2 -3.58 -2.93 -2.60
## phi1  7.06  4.86  3.94</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(pib_corr.co)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>Con el fin de completar la prueba, ahora se valida si en este modelo un término constante hace falta. Las pruebas se muestran a continuación:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pib_corr.co<span class="op">@</span>teststat</code></pre></div>
<pre><code>##               tau2     phi1
## statistic 2.517406 9.215881</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pib_corr.co<span class="op">@</span>cval</code></pre></div>
<pre><code>##       1pct  5pct 10pct
## tau2 -3.58 -2.93 -2.60
## phi1  7.06  4.86  3.94</code></pre>
<p>El valor del estadístico <span class="math inline">\(\phi_1\)</span> que prueba <span class="math inline">\(\gamma=a_0=0\)</span> resulta ser significativo comparado con los valores críticos mostrados.</p>
<p>Por lo tanto, se puede concluir que la serie contiene un raíz unitaria y una tendencia constante en el proceso generador de los datos.</p>
<p>Finalmente, se probará si diferenciando la serie una vez es suficiente para alcanzar estacionariedad. La prueba se logra utilizando como insumo para la regresión a la serie diferenciada una vez.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pib_corr2 &lt;-<span class="st"> </span><span class="kw">diff</span>(pib_corr)
pib_corr2.ct &lt;-<span class="st"> </span><span class="kw">ur.df</span>(pib_corr2,<span class="dt">type=</span><span class="st">&quot;none&quot;</span>,<span class="dt">lags=</span><span class="dv">1</span>)
<span class="kw">summary</span>(pib_corr2.ct)</code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression none 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 - 1 + z.diff.lag)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -1.034e+12 -8.491e+10  7.674e+10  3.365e+11  9.722e+11 
## 
## Coefficients:
##            Estimate Std. Error t value Pr(&gt;|t|)  
## z.lag.1    -0.01871    0.12262  -0.153   0.8802  
## z.diff.lag -0.40253    0.21583  -1.865   0.0762 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.633e+11 on 21 degrees of freedom
## Multiple R-squared:  0.1665, Adjusted R-squared:  0.08708 
## F-statistic: 2.097 on 2 and 21 DF,  p-value: 0.1478
## 
## 
## Value of test-statistic is: -0.1526 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau1 -2.66 -1.95  -1.6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pib_corr2 &lt;-<span class="st"> </span><span class="kw">diff</span>(pib_corr,<span class="dt">differences =</span> <span class="dv">2</span>)
pib_corr2.ct &lt;-<span class="st"> </span><span class="kw">ur.df</span>(pib_corr2,<span class="dt">type=</span><span class="st">&quot;none&quot;</span>,<span class="dt">lags=</span><span class="dv">0</span>)
<span class="kw">summary</span>(pib_corr2.ct)</code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression none 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 - 1)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -1.051e+12 -1.053e+11  6.029e+10  3.251e+11  9.639e+11 
## 
## Coefficients:
##         Estimate Std. Error t value Pr(&gt;|t|)    
## z.lag.1  -1.4139     0.1981  -7.137 3.72e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.529e+11 on 22 degrees of freedom
## Multiple R-squared:  0.6984, Adjusted R-squared:  0.6847 
## F-statistic: 50.94 on 1 and 22 DF,  p-value: 3.72e-07
## 
## 
## Value of test-statistic is: -7.137 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau1 -2.66 -1.95  -1.6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pib_corr2.ct<span class="op">@</span>teststat</code></pre></div>
<pre><code>##                tau1
## statistic -7.136979</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pib_corr2.ct<span class="op">@</span>cval</code></pre></div>
<pre><code>##       1pct  5pct 10pct
## tau1 -2.66 -1.95  -1.6</code></pre>
<p>La hipótesis de que el PIB a precios corrientes es <span class="math inline">\(I(2)\)</span> se comprueba rápidamente dado el estadístico <span class="math inline">\(t\)</span> con valor de -2.681622. ya que diferenciando solo una vez la serie no fue suficiente para hacer estacionaria la serie.</p>
<p>Por lo tanto. La serie del PIB a precios corrientes es <span class="math inline">\(I(2)\)</span> y de la forma <span class="math inline">\(\nabla y_t = a_0 + \gamma y_{t-1} + \epsilon_t\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(pib_corr2)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">acf</span>(pib_corr2)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-39-2.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(pib_corr2.ct)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(pib_corr)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="kw">diff</span>(pib_corr,<span class="dt">differences =</span> <span class="dv">1</span>))</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-41-2.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="kw">diff</span>(pib_corr,<span class="dt">differences =</span> <span class="dv">2</span>))</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-41-3.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">var</span>(pib_corr)</code></pre></div>
<pre><code>## [1] 3.387077e+25</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">var</span>(<span class="kw">diff</span>(pib_corr, <span class="dt">differences =</span> <span class="dv">1</span>))</code></pre></div>
<pre><code>## [1] 1.666134e+23</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">var</span>(<span class="kw">diff</span>(pib_corr, <span class="dt">differences =</span> <span class="dv">2</span>))</code></pre></div>
<pre><code>## [1] 2.345595e+23</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">var</span>(<span class="kw">diff</span>(pib_corr, <span class="dt">differences =</span> <span class="dv">3</span>))</code></pre></div>
<pre><code>## [1] 6.799588e+23</code></pre>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="orden-de-integracion-teoria.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="orden-de-integracion-lnpib-a-precios-corrientes.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/03-ADF-PIB-corr.Rmd",
"text": "Edit"
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
